### ISSUE TITLE
Viscidus cracks

### ISSUE THREAD

**Issue by Cgbd42** [gemt/server#15]
Wich value should we use for Viscidus cracks?

We can found 2 values for it, current core triggers emotes after 25/50/75 physicals hits taken, cmangos scriptdev use 50/100/150, wich one should we trust?

**Comment by gemt** [comment]
My guess is 150, but i have no vanilla sources at hand. Some extremely rough estimations:

Assumption: 
Healers do 0.4 melee hits per second (somewhere between 1.6 and 3.8 wepseed, no hit)
casters do 0.6 melee hits per second (generally faster weps, no hit)
melee/hunters do 2.36 melee hits per second (assuming DW 2.0 wepspeed with avg ~15% miss-chance and 1 yellow attk every 1.5sec) 
tanks do 1.6 hits per second 
11 healers *0.4 = 4.4/s
3 tanks * 0.6 =1.8/s
12 casters *0.6 = 7.2/s
14 melee/hunters * 33/s

total melee hits per sec: 46,4

It will take casters and healers some time to move into melee, and healers probably wont do as much, but melees are the ones who contribute by far the most anyway. 25/50/75 sounds way too easy, and if that's how it was when we tested it, it almost adds up with my estimations too, considering how fast the phase went by.

**Comment by Cgbd42** [comment]
Fixed in [this commit](https://github.com/gemt/server/commit/59d0c604cc9116f156b8734711ec47a70acb48ef)
