### ISSUE TITLE
Sartura taunt

### ISSUE THREAD

**Issue by StadenElysium** [gemt/server#30]
Need to change how the taunt immunity works to something that doesn't involve modifying the creature info.

**Comment by gemt** [comment]
Last time we tested, the guards were impossible to tank, always dropping target within ~1sec of a taunt. Is this intended?

**Comment by StadenElysium** [comment]
The guards are supposed to switch targets frequently.

**Comment by gemt** [comment]
Even when under taunt effect?

**Comment by StadenElysium** [comment]
Fixed.
