### ISSUE TITLE
Sweep timer on Ouro not resetting after submerge phase.

### ISSUE THREAD

**Issue by gemt** [gemt/server#35]
Not sure if bug or feature, but the sweep timer simply continues from whatever it was pre submerge, meaning you can end up with a knockback on spawn->sweep right after.

**Comment by StadenElysium** [comment]
There are other bosses with timers that continue to run during transitions (C'Thun), so I'll leave this unless there's evidence to suggest it should be otherwise.

**Comment by gemt** [comment]
Same thing with sand blast. Can lead to some disgusting combos. Still very killable though, and since its optional boss can probably be kept that way for a while
